# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/platform/mellanox
# Mellanox Platform-Specific Drivers
#
obj-$(CONFIG_MLX_PLATFORM)	+= mlx-platform.o
obj-$(CONFIG_MLXBF_BOOTCTL)	+= mlxbf-bootctl.o
obj-$(CONFIG_MLXBF_PMC)		+= mlxbf-pmc.o
obj-$(CONFIG_MLXBF_TMFIFO)	+= mlxbf-tmfifo.o
obj-$(CONFIG_MLXREG_DPU)	+= mlxreg-dpu.o
obj-$(CONFIG_MLXREG_HOTPLUG)	+= mlxreg-hotplug.o
obj-$(CONFIG_MLXREG_IO) += mlxreg-io.o
obj-$(CONFIG_MLXREG_LC) += mlxreg-lc.o
obj-$(CONFIG_NVSW_BMC_HID162) += nvsw-bmc-hid162.o nvsw-core.o
obj-$(CONFIG_NVSW_HOST_L1) += nvsw-host-l1.o nvsw-core.o
obj-$(CONFIG_NVSW_HOST_SPC5) += nvsw-host-spc5.o nvsw-core.o
obj-$(CONFIG_NVSW_HOST_SPC6) += nvsw-host-spc6.o nvsw-core.o
obj-$(CONFIG_NVSW_SN2201) += nvsw-sn2201.o
