# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_PENSANDO_ELBA_SOC) += elba-asic-psci.dtb \
	elba-asic-psci-mtfuji.dtb elba-asic-psci-lipari.dtb \
	elba-asic.dtb

always-y	:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
