# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_ASPEED) += \
	ast2700-evb.dtb \
	nexthop-b27-r0.dtb \
	ast2700-raw.dtb \
	ast2700-evb-s0.dtb \
	ast2700-evb-s1.dtb \
	ast2700-ncsi.dtb \
	ast2700-dcscm.dtb \
	ast2700-dcscm_ast1700-evb.dtb \
	ast2700-dcscm_ast1700-evb-dual.dtb \
	ast2700-dcscm_ast1800-evb.dtb \
	ast2700-evb-256-abr.dtb \
	ast2700-slt.dtb \
	ast2700-fpga.dtb \
	ast2700-ci-host.dtb
